Rewrite without dolittle
RaaLabs/Connectors.HealthMonitor pull request #1
Opened 2021-04-19 18:38 UTC by rafaelschlatter

- replaced old with new framework
- removed `PingTester.cs` and `BufferReader.cs` (code was duplicated)
- removed `Build`, ´bin`  and `obj` folders
- added GitHub actions
- added .sln file
- updated readme
- added .gitignore & .dockerignore

2021-04-21 09:29 UTC, srudaa commented
> * For the `Buffer` and `Ping` task in `Connector.cs` lines 42 and 43, is there a difference between using `await Task.Completed`, and `await bufferTask` and `await pingTask`? I want that we see excpetions in the the tasks on the main thread, which I think is a not the case with `Task.Run()`, but I am not sure.

@thotokraa could you answer this?

2021-04-21 11:07 UTC, thotokraa commented
> 
> 
> > * For the `Buffer` and `Ping` task in `Connector.cs` lines 42 and 43, is there a difference between using `await Task.Completed`, and `await bufferTask` and `await pingTask`? I want that we see excpetions in the the tasks on the main thread, which I think is a not the case with `Task.Run()`, but I am not sure.
> 
> @thotokraa could you answer this?

`await Task.CompletedTask` is quite literally just a constant representing a task that has already completed. It is only used to trick the compiler to make the async function compile, as any async function _requires_ an await statement inside it, otherwise it won't compile. No waiting will be enforced by this function, so declaring two tasks as variables, then awaiting for CompletedTask won't do what you think it does. What you'll want to use is `await Task.WhenAll(bufferTask, pingTask);`

If any exceptions happens inside a running async function, the exception will be thrown in the main thread when calling `.Wait()` on the task. [Check out this link to see what I mean](https://stackoverflow.com/questions/5383310/catch-an-exception-thrown-by-an-async-void-method)

2021-04-21 11:47 UTC, thotokraa requested changes

2021-04-21 11:47 UTC, thotokraa commented on Source/Connector.cs
> +        private Task Buffer()
The task should also be async.

2021-04-21 11:47 UTC, thotokraa commented on Source/Connector.cs
> +                Thread.Sleep(_configuration.Sampling);
This sleep function will sleep the entire thread, which includes all other tasks running on the thread. Please use `Task.Delay(...)` instead.

2021-04-21 11:47 UTC, thotokraa commented on Source/Connector.cs
> +        private Task Ping()
This task should be async.

2021-04-21 11:47 UTC, thotokraa commented on Source/Connector.cs
>                  Thread.Sleep(_configuration.Sampling);
You should use `Task.Delay(...)` instead when using tasks.

2021-04-21 11:51 UTC, thotokraa commented
> 
> 
> > > * For the `Buffer` and `Ping` task in `Connector.cs` lines 42 and 43, is there a difference between using `await Task.Completed`, and `await bufferTask` and `await pingTask`? I want that we see excpetions in the the tasks on the main thread, which I think is a not the case with `Task.Run()`, but I am not sure.
> > 
> > 
> > @thotokraa could you answer this?
> 
> `await Task.CompletedTask` is quite literally just a constant representing a task that has already completed. It is only used to trick the compiler to make the async function compile, as any async function _requires_ an await statement inside it, otherwise it won't compile. No waiting will be enforced by this function, so declaring two tasks as variables, then awaiting for CompletedTask won't do what you think it does. What you'll want to use is `await Task.WhenAll(bufferTask, pingTask);`
> 
> If any exceptions happens inside a running async function, the exception will be thrown in the main thread when calling `.Wait()` on the task. [Check out this link to see what I mean](https://stackoverflow.com/questions/5383310/catch-an-exception-thrown-by-an-async-void-method)

Looking at the code again, I see that neither `Buffer()` nor `Ping()` will ever return, which means that even if there was a `Wait()` function somewhere in the code to wait for `Connector.Run()` to finish, it would never happen. As I also see now, the connector is declared as a task through `ApplicationBuilder.WithTask<T>()`, so there would be no way to actually wait for the task to throw an exception. There's no way that I can see for handling these exceptions on the main thread, but why would you want this?

2021-04-22 10:12 UTC, rafaelschlatter commented
> > > > * For the `Buffer` and `Ping` task in `Connector.cs` lines 42 and 43, is there a difference between using `await Task.Completed`, and `await bufferTask` and `await pingTask`? I want that we see excpetions in the the tasks on the main thread, which I think is a not the case with `Task.Run()`, but I am not sure.
> > > 
> > > 
> > > @thotokraa could you answer this?
> > 
> > 
> > `await Task.CompletedTask` is quite literally just a constant representing a task that has already completed. It is only used to trick the compiler to make the async function compile, as any async function _requires_ an await statement inside it, otherwise it won't compile. No waiting will be enforced by this function, so declaring two tasks as variables, then awaiting for CompletedTask won't do what you think it does. What you'll want to use is `await Task.WhenAll(bufferTask, pingTask);`
> > If any exceptions happens inside a running async function, the exception will be thrown in the main thread when calling `.Wait()` on the task. [Check out this link to see what I mean](https://stackoverflow.com/questions/5383310/catch-an-exception-thrown-by-an-async-void-method)
> 
> Looking at the code again, I see that neither `Buffer()` nor `Ping()` will ever return, which means that even if there was a `Wait()` function somewhere in the code to wait for `Connector.Run()` to finish, it would never happen. As I also see now, the connector is declared as a task through `ApplicationBuilder.WithTask<T>()`, so there would be no way to actually wait for the task to throw an exception. There's no way that I can see for handling these exceptions on the main thread, but why would you want this?

If we are not notified of these

2021-04-22 10:18 UTC, rafaelschlatter commented on Source/Connector.cs
> +        private Task Buffer()
Done

2021-04-22 10:18 UTC, rafaelschlatter commented on Source/Connector.cs
> +                Thread.Sleep(_configuration.Sampling);
Done

2021-04-22 11:14 UTC, thotokraa approved these changes

2021-04-22 11:14 UTC, merged